/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthorDto"][];
                        "application/json": components["schemas"]["AuthorDto"][];
                        "text/json": components["schemas"]["AuthorDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddAuthorCommand"];
                    "text/json": components["schemas"]["AddAuthorCommand"];
                    "application/*+json": components["schemas"]["AddAuthorCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthorDto"];
                        "application/json": components["schemas"]["AuthorDto"];
                        "text/json": components["schemas"]["AuthorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthorDto"];
                        "application/json": components["schemas"]["AuthorDto"];
                        "text/json": components["schemas"]["AuthorDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookDto"][];
                        "application/json": components["schemas"]["BookDto"][];
                        "text/json": components["schemas"]["BookDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddBookCommand"];
                    "text/json": components["schemas"]["AddBookCommand"];
                    "application/*+json": components["schemas"]["AddBookCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookDto"];
                        "application/json": components["schemas"]["BookDto"];
                        "text/json": components["schemas"]["BookDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookDto"];
                        "application/json": components["schemas"]["BookDto"];
                        "text/json": components["schemas"]["BookDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateBookCommand"];
                    "text/json": components["schemas"]["UpdateBookCommand"];
                    "application/*+json": components["schemas"]["UpdateBookCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookDto"];
                        "application/json": components["schemas"]["BookDto"];
                        "text/json": components["schemas"]["BookDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    before?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookEventPageDto"];
                        "application/json": components["schemas"]["BookEventPageDto"];
                        "text/json": components["schemas"]["BookEventPageDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    before?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    bookId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookEventPageDto"];
                        "application/json": components["schemas"]["BookEventPageDto"];
                        "text/json": components["schemas"]["BookEventPageDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddAuthorCommand: {
            name?: string | null;
        };
        AddBookCommand: {
            title?: string | null;
            description?: string | null;
            /** Format: date */
            publishedDate?: string;
            authorIds?: string[] | null;
        };
        AuthorDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
        };
        BookDto: {
            /** Format: uuid */
            id?: string;
            title?: string | null;
            description?: string | null;
            /** Format: date */
            publishedDate?: string;
            authors?: components["schemas"]["AuthorDto"][] | null;
        };
        BookEventDto: {
            /** Format: int64 */
            id?: number;
            /** Format: uuid */
            bookId?: string;
            changeType?: string | null;
            newValue?: string | null;
            /** Format: date-time */
            occurredAt?: string;
        };
        BookEventPageDto: {
            items?: components["schemas"]["BookEventDto"][] | null;
            /** Format: int64 */
            nextCursor?: number | null;
        };
        UpdateBookCommand: {
            /** Format: uuid */
            id?: string;
            title?: string | null;
            description?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
